import { HGoldType, HuasenghengDataType } from "../../src/models/huasengheng";

export const huasengsengPriceData1: HuasenghengDataType = {
  GoldType: HGoldType.HSH,
  GoldCode: "96.50",
  Buy: "40,410",
  Sell: "40,460",
  TimeUpdate: "2024-08-06T08:47:14",
  BuyChange: -10.0,
  SellChange: -10.0,
  PresentDate: "",
  FxAsk: null,
  FxBid: null,
  Bid: null,
  Ask: null,
  QtyBid: null,
  QtyAsk: null,
  Discount: null,
  Premium: null,
  Increment: null,
  SourcePrice: null,
  StrTimeUpdate: "อัพเดตล่าสุด วันที่ 6 ส.ค. 2567 เวลา 08:47:14 น.",
};

export const huasengsengPriceData2: HuasenghengDataType = {
  GoldType: HGoldType.HSH,
  GoldCode: "96.50",
  Buy: "40,610",
  Sell: "40,660",
  TimeUpdate: "2024-08-06T08:47:14",
  BuyChange: 200.0,
  SellChange: 200.0,
  PresentDate: "",
  FxAsk: null,
  FxBid: null,
  Bid: null,
  Ask: null,
  QtyBid: null,
  QtyAsk: null,
  Discount: null,
  Premium: null,
  Increment: null,
  SourcePrice: null,
  StrTimeUpdate: "อัพเดตล่าสุด วันที่ 6 ส.ค. 2567 เวลา 08:47:15 น.",
};

export const huasengsengPriceData3: HuasenghengDataType = {
  GoldType: HGoldType.HSH,
  GoldCode: "96.50",
  Buy: "40,210",
  Sell: "40,260",
  TimeUpdate: "2024-08-06T08:47:14",
  BuyChange: -200.0,
  SellChange: -200.0,
  PresentDate: "",
  FxAsk: null,
  FxBid: null,
  Bid: null,
  Ask: null,
  QtyBid: null,
  QtyAsk: null,
  Discount: null,
  Premium: null,
  Increment: null,
  SourcePrice: null,
  StrTimeUpdate: "อัพเดตล่าสุด วันที่ 6 ส.ค. 2567 เวลา 08:47:16 น.",
};

export const huasengsengPriceData4: HuasenghengDataType = {
  GoldType: HGoldType.HSH,
  GoldCode: "96.50",
  Buy: "40,420",
  Sell: "40,470",
  TimeUpdate: "2024-08-06T08:47:14",
  BuyChange: 20.0,
  SellChange: 20.0,
  PresentDate: "",
  FxAsk: null,
  FxBid: null,
  Bid: null,
  Ask: null,
  QtyBid: null,
  QtyAsk: null,
  Discount: null,
  Premium: null,
  Increment: null,
  SourcePrice: null,
  StrTimeUpdate: "อัพเดตล่าสุด วันที่ 6 ส.ค. 2567 เวลา 08:47:17 น.",
};