-- public.goldprice definition
-- Drop table
-- DROP TABLE public.goldprice;
CREATE TABLE
    public.goldprice (
        id int8 GENERATED BY DEFAULT AS IDENTITY (
            INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
        ) NOT NULL,
        buy int8 NOT NULL,
        sell int8 NULL,
        buy_change int8 NULL,
        sell_change int8 NULL,
        time_update_string text NULL,
        time_update text NULL,
        created_time timestamptz NULL,
        CONSTRAINT goldprice_pkey PRIMARY KEY (id)
    );

CREATE INDEX goldprice_created_time_idx ON public.goldprice USING btree (created_time);